import { createFileRoute } from '@tanstack/react-router'
import { useEffect, useRef, useState } from 'react'
import { AuthChat } from '@/components/AuthChat'
import { ensureSolaProfile, supabase } from '@/lib/supabase'
import { getDevnetBalance } from '@/lib/solana'

export const Route = createFileRoute('/app')({ component: ChatApp })
type Message = { from: 'bot' | 'user'; text: string; actions?: string[] }

function ChatApp() {
  const [messages, setMessages] = useState<Message[]>([{ from: 'bot', text: 'Bonjour, je suis Sola. Je peux t’aider à connecter ton wallet, consulter tes informations et préparer une opération. Que veux-tu faire ?', actions: ['Connecter mon wallet', '/balance', '/history'] }])
  const feedRef = useRef<HTMLDivElement>(null)
  const [input, setInput] = useState(''); const [connected, setConnected] = useState(false); const [walletAddress, setWalletAddress] = useState(''); const [busy, setBusy] = useState(false)
  const [demoMode, setDemoMode] = useState(false)
  const [authChecked, setAuthChecked] = useState(false); const [authenticated, setAuthenticated] = useState(false)
  useEffect(() => { let active = true; if (!supabase) { setAuthChecked(true); return }; supabase.auth.getSession().then(async ({ data }) => { if (!active) return; setAuthenticated(Boolean(data.session?.user)); setAuthChecked(true); if (data.session?.user) await ensureSolaProfile(data.session.user) }); const { data: listener } = supabase.auth.onAuthStateChange((_event, session) => { setAuthenticated(Boolean(session)); setAuthChecked(true) }); return () => { active = false; listener.subscription.unsubscribe() } }, [])
  useEffect(() => { const feed = feedRef.current; if (feed) feed.scrollTo({ top: feed.scrollHeight, behavior: 'smooth' }) }, [messages])
  const connect = async () => { setBusy(true); if (demoMode) { const address = 'Demo7SolaWallet1111111111111111111111111111111'; setWalletAddress(address); setConnected(true); setMessages(m => [...m, { from:'bot', text:`Mode démo actif. Wallet simulé : ${address.slice(0,4)}…${address.slice(-4)} sur Solana devnet. Aucune donnée réelle ni opération réelle n’est utilisée.`, actions:['/balance','/history','/withdraw'] }]); setBusy(false); return } const win = window as unknown as { solana?: { connect?: () => Promise<{ publicKey?: { toString: () => string } }>; isPhantom?: boolean }; phantom?: { solana?: { connect?: () => Promise<{ publicKey?: { toString: () => string } }>; isPhantom?: boolean } } }; const provider = win.phantom?.solana ?? win.solana; if (!provider?.connect) { setMessages(m => [...m, { from:'bot', text:'Je ne trouve pas Phantom dans ce navigateur. Installe Phantom ou ouvre Sola dans un environnement compatible Solana.' }]); setBusy(false); return } try { const { data } = await supabase?.auth.getSession() ?? { data: { session: null } }; const res = await provider.connect(); const address = res.publicKey?.toString(); if (!data.session?.user || !address || !supabase) throw new Error('SESSION_OR_WALLET_MISSING'); const { error } = await supabase.from('sola_wallets').upsert({ user_id: data.session.user.id, public_address: address, network: 'devnet', active: true }, { onConflict: 'user_id,public_address,network' }); if (error) throw error; setWalletAddress(address); setConnected(true); setMessages(m => [...m, { from:'bot', text:`Wallet connecté : ${address.slice(0,4)}…${address.slice(-4)} sur Solana devnet. Tu peux maintenant utiliser /balance, /progress, /history ou /withdraw.`, actions:['/balance','/withdraw'] }]) } catch { setMessages(m => [...m, { from:'bot', text:'La connexion Phantom n’a pas pu être enregistrée. Vérifie que tu es connecté à Sola et sur le réseau devnet.' }]) } setBusy(false) }
  const command = async (raw: string) => { const cmd = raw.trim().toLowerCase(); setMessages(m => [...m, { from:'user', text:raw }]); if (cmd === '/start') return setMessages(m => [...m, { from:'bot', text:'Bienvenue sur Sola. Connecte ton wallet pour commencer.', actions:['Connecter mon wallet'] }]); if (!connected && cmd !== 'connecter mon wallet') return setMessages(m => [...m, { from:'bot', text:'Connecte d’abord ton wallet. Je ne peux pas consulter de données sans adresse publique vérifiée.', actions:['Connecter mon wallet'] }]); if (cmd === '/balance') { if (demoMode) return setMessages(m => [...m, { from:'bot', text:'Mode démo : le solde n’est pas connecté à la blockchain. Cette valeur est volontairement indisponible jusqu’à la configuration de l’authentification et de Phantom.' }]); setMessages(m => [...m, { from:'bot', text:'Je consulte le réseau Solana devnet…' }]); try { const balance = await getDevnetBalance(walletAddress); setMessages(m => [...m, { from:'bot', text:`Solde SOL réel : ${balance.sol.toFixed(4)} SOL. Synchronisé à l’instant. USDT : indisponible sur cette configuration devnet.` }]) } catch { setMessages(m => [...m, { from:'bot', text:'Le RPC Solana devnet est temporairement indisponible. Aucun solde ne sera estimé.' }]) }; return }; if (cmd === '/progress') return setMessages(m => [...m, { from:'bot', text:'La progression sera disponible après validation des données de compte. Sola n’affichera jamais une estimation présentée comme un résultat réel.' }]); if (cmd === '/history') return setMessages(m => [...m, { from:'bot', text:'Aucune transaction synchronisée dans cette session. La connexion RPC affichera ici uniquement l’historique on-chain vérifié.' }]); if (cmd === '/withdraw') return setMessages(m => [...m, { from:'bot', text:'Pour préparer un transfert, indique le montant. Je te demanderai ensuite l’adresse publique et une confirmation complète avant toute action.' }]); return setMessages(m => [...m, { from:'bot', text:'Je reconnais les commandes /start, /balance, /progress, /history et /withdraw. Tu peux aussi choisir une action ci-dessous.', actions:['/balance','/progress','/history','/withdraw'] }]) }
  const send = (value = input) => { if (!value.trim()) return; setInput(''); if (value === 'Connecter mon wallet') return connect(); void command(value) }
  if (!authChecked) return <main className="chat-page"><section className="chat-shell"><div className="chat-feed"><div className="message-row bot"><div className="message-bubble">Je prépare ton espace Sola…</div></div></div></section></main>
  if (!authenticated) return <main className="chat-page"><section className="chat-shell"><div className="chat-feed"><AuthChat onAuthenticated={() => setAuthenticated(true)} onDemo={() => { const demoAddress = 'Demo7SolaWallet1111111111111111111111111111111'; setDemoMode(true); setAuthenticated(true); setConnected(true); setWalletAddress(demoAddress); setMessages(m => [...m, { from:'bot', text:`Mode démo actif. Wallet simulé déjà connecté : ${demoAddress.slice(0,4)}…${demoAddress.slice(-4)}. Tu peux tester les commandes immédiatement. Aucune donnée réelle ni opération réelle n’est utilisée.`, actions:['/balance','/history','/withdraw'] }]) }} /></div><div className="chat-controls"><form className="chat-composer" onSubmit={e=>{e.preventDefault();send()}}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Écrire un message à Sola…" aria-label="Message"/><button type="submit" aria-label="Envoyer">↗</button></form><p className="chat-disclaimer">Tu peux parler à Sola ici. Les données du wallet seront disponibles après connexion.</p></div></section></main>
  return <main className="chat-page"><section className="chat-shell"><div ref={feedRef} className="chat-feed">{messages.map((message,index)=><div className={`message-row ${message.from}`} key={`${message.text}-${index}`}><div className="message-bubble">{message.text}</div>{message.actions && <div className="message-actions">{message.actions.map(action=><button key={action} onClick={()=>send(action)} disabled={busy}>{action === 'Connecter mon wallet' ? (busy ? 'Connexion…' : action) : action}</button>)}</div>}</div>)}</div><div className="chat-controls"><div className="command-hints"><button onClick={()=>send('/balance')}>/balance</button><button onClick={()=>send('/progress')}>/progress</button><button onClick={()=>send('/withdraw')}>/withdraw</button></div><form className="chat-composer" onSubmit={e=>{e.preventDefault();send()}}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Écrire un message à Sola…" aria-label="Message"/><button type="submit" aria-label="Envoyer">↗</button></form><p className="chat-disclaimer">Sola ne demande jamais de phrase secrète ni de clé privée. Toute action sensible reste vérifiable dans votre wallet.</p></div></section></main>
}
