import { createFileRoute, Link, useNavigate } from '@tanstack/react-router'
import { useState, type FormEvent } from 'react'
import { ensureSolaProfile, supabase } from '@/lib/supabase'

export const Route = createFileRoute('/connexion')({ component: Login })

function Login() {
  const navigate = useNavigate(); const [email, setEmail] = useState(''); const [otp, setOtp] = useState(''); const [otpSent, setOtpSent] = useState(false); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(''); const [error, setError] = useState('')
  const google = async () => { setBusy(true); setError(''); if (!supabase) { setError('La connexion n’est pas encore configurée.'); setBusy(false); return }; const { error: authError } = await supabase.auth.signInWithOAuth({ provider: 'google', options: { redirectTo: `${window.location.origin}/app` } }); if (authError) setError(authError.message); setBusy(false) }
  const magicLink = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); setNotice(''); if (!supabase) { setError('La connexion n’est pas configurée.'); setBusy(false); return }; const { error: authError } = await supabase.auth.signInWithOtp({ email, options: { emailRedirectTo: `${window.location.origin}/app` } }); if (authError) setError(authError.message); else { setOtpSent(true); setNotice('Code envoyé. Vérifie ta boîte mail pour continuer.') }; setBusy(false) }
  const verifyOtp = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); if (!supabase) return; const { data, error: authError } = await supabase.auth.verifyOtp({ email, token: otp, type: 'email' }); if (authError || !data.user) setError('Code invalide ou expiré.'); else { const profile = await ensureSolaProfile(data.user); if (profile.error) setError('Connexion réussie, mais le profil n’a pas pu être préparé.'); else navigate({ to: '/app' }) }; setBusy(false) }
  return <main className="auth-page"><div className="auth-shell"><Link to="/" className="brand"><span className="brand-mark">S</span><span>Sola</span></Link><div className="auth-panel"><p className="eyebrow">VOTRE ESPACE SOLA</p><h1>Commencer simplement.</h1><p className="muted">Connectez-vous avant de connecter votre wallet. Sola ne demande jamais votre phrase secrète.</p><button className="secondary-action auth-button auth-google" onClick={google} disabled={busy}><span className="google-mark">G</span>{busy ? 'Connexion en cours…' : 'Continuer avec Google'}</button><div className="auth-divider"><span /> ou <span /></div>{!otpSent ? <form onSubmit={magicLink}><label htmlFor="email">Votre adresse email</label><div className="auth-email-row"><input id="email" type="email" required value={email} onChange={event => setEmail(event.target.value)} placeholder="vous@exemple.com" /><button className="primary-action" type="submit" disabled={busy}>{busy ? '…' : 'Recevoir le code'}</button></div></form> : <form onSubmit={verifyOtp}><label htmlFor="otp">Code reçu par email</label><div className="auth-email-row"><input id="otp" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} required value={otp} onChange={event => setOtp(event.target.value.replace(/\D/g, ''))} placeholder="000000" /><button className="primary-action" type="submit" disabled={busy}>{busy ? '…' : 'Vérifier'}</button></div><button type="button" className="auth-resend" onClick={() => setOtpSent(false)}>Utiliser une autre adresse</button></form>}{notice && <p className="auth-notice">{notice}</p>}{error && <p className="auth-error">{error}</p>}<p className="auth-legal">Après la connexion, vous pourrez connecter Phantom et consulter vos données réelles sur Solana.</p></div><Link to="/" className="back-link">← Retour à l’accueil</Link></div></main>
}
