import { useState, type FormEvent } from 'react'
import { ensureSolaProfile, supabase } from '@/lib/supabase'

export function AuthChat({ onAuthenticated, onDemo }: { onAuthenticated: () => void; onDemo: () => void }) {
  const [email, setEmail] = useState(''); const [otp, setOtp] = useState(''); const [sent, setSent] = useState(false); const [showEmail, setShowEmail] = useState(false); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(''); const [error, setError] = useState('')
  const google = async () => { if (!supabase) return setError('Connexion indisponible.'); setBusy(true); const { error: authError } = await supabase.auth.signInWithOAuth({ provider: 'google', options: { redirectTo: `${window.location.origin}/app` } }); if (authError) setError(authError.message); setBusy(false) }
  const send = async (event: FormEvent) => { event.preventDefault(); if (!supabase) return setError('Connexion indisponible.'); setBusy(true); setError(''); const { error: authError } = await supabase.auth.signInWithOtp({ email, options: { emailRedirectTo: `${window.location.origin}/app` } }); if (authError) setError(authError.message); else { setSent(true); setNotice('Je viens de t’envoyer un code.'); } setBusy(false) }
  const verify = async (event: FormEvent) => { event.preventDefault(); if (!supabase) return; setBusy(true); const { data, error: authError } = await supabase.auth.verifyOtp({ email, token: otp, type: 'email' }); if (authError || !data.user) setError('Ce code est invalide ou expiré.'); else { await ensureSolaProfile(data.user); onAuthenticated() }; setBusy(false) }
  return <div className="auth-chat"><div className="message-row bot"><div className="message-bubble">Bonjour, je suis Sola. Je peux t’aider à comprendre ton wallet et préparer des actions vérifiables.</div></div><div className="message-row bot"><div className="message-bubble">Pour commencer, connecte-toi à ton espace. Ensuite, on connectera Phantom ensemble.</div><div className="auth-actions"><button className="google-auth-button" onClick={google} disabled={busy}><svg className="google-logo" viewBox="0 0 24 24" aria-hidden="true"><path fill="#4285F4" d="M21.35 12.23c0-.72-.06-1.42-.18-2.09H12v3.96h5.24a4.48 4.48 0 0 1-1.94 2.94v2.45h3.14c1.84-1.69 2.91-4.18 2.91-7.26Z"/><path fill="#34A853" d="M12 21.5c2.63 0 4.84-.87 6.45-2.36l-3.14-2.45c-.87.58-1.98.93-3.31.93-2.54 0-4.69-1.71-5.46-4.01H3.3v2.53A9.74 9.74 0 0 0 12 21.5Z"/><path fill="#FBBC05" d="M6.54 13.61A5.86 5.86 0 0 1 6.23 12c0-.56.1-1.11.31-1.61V7.86H3.3A9.74 9.74 0 0 0 2.25 12c0 1.57.38 3.06 1.05 4.14l3.24-2.53Z"/><path fill="#EA4335" d="M12 6.38c1.43 0 2.71.49 3.72 1.45l2.79-2.79C16.84 3.37 14.63 2.5 12 2.5a9.74 9.74 0 0 0-8.7 5.36l3.24 2.53c.77-2.3 2.92-4.01 5.46-4.01Z"/></svg><span>Continuer avec Google</span></button><button className="magic-link-toggle" type="button" onClick={() => setShowEmail(value => !value)}>{showEmail ? 'Masquer le lien magique' : 'Ou recevoir un lien magique'}</button><button className="demo-auth-button" type="button" onClick={onDemo}>Entrer en mode démo</button></div></div>{showEmail && <div className="auth-chat__inline">{!sent ? <form onSubmit={send}><label htmlFor="chat-email">Adresse email</label><div className="auth-email-row"><input id="chat-email" type="email" required value={email} onChange={event => setEmail(event.target.value)} placeholder="vous@exemple.com" /><button className="primary-action" type="submit" disabled={busy}>{busy ? '…' : 'Recevoir le lien'}</button></div></form> : <form onSubmit={verify}><label htmlFor="chat-otp">Entre le code reçu par email</label><div className="auth-email-row"><input id="chat-otp" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} required value={otp} onChange={event => setOtp(event.target.value.replace(/\D/g, ''))} placeholder="000000" /><button className="primary-action" type="submit" disabled={busy}>{busy ? '…' : 'Valider'}</button></div></form>}{notice && <p className="auth-notice">{notice}</p>}{error && <p className="auth-error">{error}</p>}</div>}<p className="chat-disclaimer">Sola ne demande jamais de phrase secrète ni de clé privée.</p></div>
}
